// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wauR2tk1hPNKxeSBCX7ndF
// Component: KYOCF7zeGyoX

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Header from "../../Header"; // plasmic-import: fMrxAl7coXSG/component
import Footer2 from "../../Footer2"; // plasmic-import: 9pDOvBRTOpt9/component

import { useScreenVariants as useScreenVariants_2YPqM3KDWg } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 2yPqM3-kD-WG/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: wauR2tk1hPNKxeSBCX7ndF/projectcss
import sty from "./PlasmicNewsAndActivity.module.css"; // plasmic-import: KYOCF7zeGyoX/css

import _14655891761535698998SvgIcon from "./icons/PlasmicIcon___14655891761535698998Svg"; // plasmic-import: YG3YAEM_AYjb/icon

createPlasmicElementProxy;

export type PlasmicNewsAndActivity__VariantMembers = {};
export type PlasmicNewsAndActivity__VariantsArgs = {};
type VariantPropType = keyof PlasmicNewsAndActivity__VariantsArgs;
export const PlasmicNewsAndActivity__VariantProps =
  new Array<VariantPropType>();

export type PlasmicNewsAndActivity__ArgsType = {
  pic?: React.ReactNode;
  slot?: React.ReactNode;
  pic2?: React.ReactNode;
  slot2?: React.ReactNode;
  pic3?: React.ReactNode;
  slot3?: React.ReactNode;
  pic4?: React.ReactNode;
  slot4?: React.ReactNode;
  pic5?: React.ReactNode;
  slot5?: React.ReactNode;
  pic6?: React.ReactNode;
  slot6?: React.ReactNode;
  pic7?: React.ReactNode;
  slot7?: React.ReactNode;
  pic8?: React.ReactNode;
  slot8?: React.ReactNode;
  pic9?: React.ReactNode;
  slot9?: React.ReactNode;
  pic10?: React.ReactNode;
  slot10?: React.ReactNode;
};
type ArgPropType = keyof PlasmicNewsAndActivity__ArgsType;
export const PlasmicNewsAndActivity__ArgProps = new Array<ArgPropType>(
  "pic",
  "slot",
  "pic2",
  "slot2",
  "pic3",
  "slot3",
  "pic4",
  "slot4",
  "pic5",
  "slot5",
  "pic6",
  "slot6",
  "pic7",
  "slot7",
  "pic8",
  "slot8",
  "pic9",
  "slot9",
  "pic10",
  "slot10"
);

export type PlasmicNewsAndActivity__OverridesType = {
  page?: Flex__<"div">;
  header?: Flex__<typeof Header>;
  bannerHeader?: Flex__<"div">;
  h1?: Flex__<"h1">;
  productAndService?: Flex__<"div">;
  columns?: Flex__<"div">;
  footer2?: Flex__<typeof Footer2>;
};

export interface DefaultNewsAndActivityProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNewsAndActivity__RenderFunc(props: {
  variants: PlasmicNewsAndActivity__VariantsArgs;
  args: PlasmicNewsAndActivity__ArgsType;
  overrides: PlasmicNewsAndActivity__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_2YPqM3KDWg()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <Stack__
          as={"div"}
          data-plasmic-name={"page"}
          data-plasmic-override={overrides.page}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.page
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div
            data-plasmic-name={"bannerHeader"}
            data-plasmic-override={overrides.bannerHeader}
            className={classNames(projectcss.all, sty.bannerHeader)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__wk4Ci)}>
              <div className={classNames(projectcss.all, sty.freeBox__bqKne)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__cToZx)}
                >
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "\u0e02\u0e48\u0e32\u0e27\u0e2a\u0e32\u0e23\u0e41\u0e25\u0e30\u0e01\u0e34\u0e08\u0e01\u0e23\u0e23\u0e21"
                      : "\u0e02\u0e48\u0e32\u0e27\u0e2a\u0e32\u0e23\u0e41\u0e25\u0e30\u0e01\u0e34\u0e08\u0e01\u0e23\u0e23\u0e21"}
                  </h1>
                </Stack__>
              </div>
            </div>
          </div>
          <Stack__
            as={"div"}
            data-plasmic-name={"productAndService"}
            data-plasmic-override={overrides.productAndService}
            hasGap={true}
            className={classNames(projectcss.all, sty.productAndService)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___28Bb3)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"columns"}
                data-plasmic-override={overrides.columns}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns)}
              >
                <div className={classNames(projectcss.all, sty.column__kMyc)}>
                  <Stack__
                    as={PlasmicLink__}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link___6KwxZ
                    )}
                    component={Link}
                    href={`/PERMATANK และถังน้ำมันแบบต่างๆ`}
                    platform={"nextjs"}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__o5LYh)}
                    >
                      {renderPlasmicSlot({
                        defaultContents: (
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__zBknU)}
                            displayHeight={"250px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/psd_j/images/_4664413729649586456683132441591559472871573NJpg.jpg",
                              fullWidth: 2048,
                              fullHeight: 1536,
                              aspectRatio: undefined
                            }}
                          />
                        ),

                        value: args.pic
                      })}
                    </div>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__y7FOq)}
                    >
                      {renderPlasmicSlot({
                        defaultContents: (
                          <React.Fragment>
                            <Stack__
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__lDu2U
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__etSb5
                                )}
                              >
                                <_14655891761535698998SvgIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg___8Ga6C
                                  )}
                                  role={"img"}
                                />
                              </div>
                              <Stack__
                                as={"div"}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__zS4Fs
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__rVnz8
                                  )}
                                >
                                  {
                                    "\u0e18\u0e31\u0e19\u0e27\u0e32\u0e04\u0e21 27, 2024"
                                  }
                                </div>
                              </Stack__>
                            </Stack__>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__upfAl
                              )}
                            >
                              {
                                "\u0e1a\u0e23\u0e34\u0e29\u0e31\u0e17\u0e1c\u0e14\u0e38\u0e07\u0e28\u0e34\u0e25\u0e1b\u0e4c\u0e27\u0e34\u0e28\u0e27\u0e01\u0e32\u0e23 \u0e08\u0e33\u0e01\u0e31\u0e14 \u0e40\u0e02\u0e49\u0e32\u0e23\u0e31\u0e1a\u0e21\u0e2d\u0e1a\u0e23\u0e32\u0e07\u0e27\u0e31\u0e25\u0e23\u0e30\u0e14\u0e31\u0e1a\u0e1b\u0e23\u0e30\u0e40\u0e17\u0e28"
                              }
                            </div>
                          </React.Fragment>
                        ),
                        value: args.slot
                      })}
                    </Stack__>
                  </Stack__>
                </div>
                <div className={classNames(projectcss.all, sty.column__kOuSc)}>
                  <Stack__
                    as={PlasmicLink__}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__ws85B
                    )}
                    component={Link}
                    href={`/PERMATANK และถังน้ำมันแบบต่างๆ`}
                    platform={"nextjs"}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__o0G)}
                    >
                      {renderPlasmicSlot({
                        defaultContents: (
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__kYOlG)}
                            displayHeight={"250px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/psd_j/images/_29120584053472534086876881457757044295190479NJpg.jpg",
                              fullWidth: 800,
                              fullHeight: 600,
                              aspectRatio: undefined
                            }}
                          />
                        ),

                        value: args.pic2
                      })}
                    </div>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___8Tm3C
                      )}
                    >
                      {renderPlasmicSlot({
                        defaultContents: (
                          <React.Fragment>
                            <Stack__
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox___25DD
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__q9Jin
                                )}
                              >
                                <_14655891761535698998SvgIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__x0OnD
                                  )}
                                  role={"img"}
                                />
                              </div>
                              <Stack__
                                as={"div"}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__zy1U
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__e71Iq
                                  )}
                                >
                                  {
                                    "\u0e18\u0e31\u0e19\u0e27\u0e32\u0e04\u0e21 27, 2024"
                                  }
                                </div>
                              </Stack__>
                            </Stack__>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__zkm0X
                              )}
                            >
                              {
                                "\u0e1a\u0e23\u0e34\u0e29\u0e31\u0e17 \u0e1c\u0e14\u0e38\u0e07\u0e28\u0e34\u0e25\u0e1b\u0e4c\u0e27\u0e34\u0e28\u0e27\u0e01\u0e32\u0e23 \u0e08\u0e33\u0e01\u0e31\u0e14 \u0e44\u0e14\u0e49\u0e23\u0e31\u0e1a\u0e43\u0e1a\u0e23\u0e31\u0e1a\u0e23\u0e2d\u0e07 \u0e2d\u0e38\u0e15\u0e2a\u0e32\u0e2b\u0e01\u0e23\u0e23\u0e21\u0e2a\u0e35\u0e40\u0e02\u0e35\u0e22\u0e27"
                              }
                            </div>
                          </React.Fragment>
                        ),
                        value: args.slot2
                      })}
                    </Stack__>
                  </Stack__>
                </div>
                <div className={classNames(projectcss.all, sty.column__zzWgy)}>
                  <Stack__
                    as={PlasmicLink__}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__h4We
                    )}
                    component={Link}
                    href={`/PERMATANK และถังน้ำมันแบบต่างๆ`}
                    platform={"nextjs"}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__sPbVx)}
                    >
                      {renderPlasmicSlot({
                        defaultContents: (
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__lIwOj)}
                            displayHeight={"250px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/psd_j/images/_4444833488493994405575683439209113144118689NJpg.jpg",
                              fullWidth: 1479,
                              fullHeight: 1109,
                              aspectRatio: undefined
                            }}
                          />
                        ),

                        value: args.pic3
                      })}
                    </div>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___6C7Hn
                      )}
                    >
                      {renderPlasmicSlot({
                        defaultContents: (
                          <React.Fragment>
                            <Stack__
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__tyd43
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__ay28R
                                )}
                              >
                                <_14655891761535698998SvgIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__bbGud
                                  )}
                                  role={"img"}
                                />
                              </div>
                              <Stack__
                                as={"div"}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox___6BjxX
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__muhvP
                                  )}
                                >
                                  {
                                    "\u0e18\u0e31\u0e19\u0e27\u0e32\u0e04\u0e21 27, 2024"
                                  }
                                </div>
                              </Stack__>
                            </Stack__>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__tXFe4
                              )}
                            >
                              {
                                "\u0e1a\u0e23\u0e34\u0e29\u0e31\u0e17\u0e1c\u0e14\u0e38\u0e07\u0e28\u0e34\u0e25\u0e1b\u0e4c\u0e27\u0e34\u0e28\u0e27\u0e01\u0e32\u0e23 \u0e08\u0e33\u0e01\u0e31\u0e14 \u0e44\u0e14\u0e49\u0e23\u0e31\u0e1a\u0e21\u0e2d\u0e1a\u0e40\u0e01\u0e35\u0e22\u0e23\u0e15\u0e34\u0e1a\u0e31\u0e15\u0e23 \u0e14\u0e49\u0e32\u0e19\u0e04\u0e27\u0e32\u0e21\u0e1b\u0e25\u0e2d\u0e14\u0e20\u0e31\u0e22 \u0e43\u0e19\u0e42\u0e04\u0e23\u0e07\u0e01\u0e32\u0e23 \u201cPATHUMTHANI OCCUPATIONAL HEALTH AND SAFETY PROJECT CONTEST 2024\u201d"
                              }
                            </div>
                          </React.Fragment>
                        ),
                        value: args.slot3
                      })}
                    </Stack__>
                  </Stack__>
                </div>
                <div className={classNames(projectcss.all, sty.column__rVkLa)}>
                  <Stack__
                    as={PlasmicLink__}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__mb4UM
                    )}
                    component={Link}
                    href={`/PERMATANK และถังน้ำมันแบบต่างๆ`}
                    platform={"nextjs"}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__jUdi0)}
                    >
                      {renderPlasmicSlot({
                        defaultContents: (
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__zUgxW)}
                            displayHeight={"250px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/psd_j/images/atgNewJpg.jpg",
                              fullWidth: 1600,
                              fullHeight: 900,
                              aspectRatio: undefined
                            }}
                          />
                        ),

                        value: args.pic4
                      })}
                    </div>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___5QiNy
                      )}
                    >
                      {renderPlasmicSlot({
                        defaultContents: (
                          <React.Fragment>
                            <Stack__
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__sPhwl
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__nRqvh
                                )}
                              >
                                <_14655891761535698998SvgIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__v3ZnF
                                  )}
                                  role={"img"}
                                />
                              </div>
                              <Stack__
                                as={"div"}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__ru7Ym
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__jWond
                                  )}
                                >
                                  {
                                    "\u0e18\u0e31\u0e19\u0e27\u0e32\u0e04\u0e21 27, 2024"
                                  }
                                </div>
                              </Stack__>
                            </Stack__>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__vPcIn
                              )}
                            >
                              {
                                "\u0e27\u0e31\u0e19\u0e17\u0e35\u0e48 8 \u0e1e\u0e24\u0e28\u0e08\u0e34\u0e01\u0e32\u0e22\u0e19 2567 \u0e1c\u0e39\u0e49\u0e1a\u0e23\u0e34\u0e2b\u0e32\u0e23\u0e1a\u0e23\u0e34\u0e29\u0e31\u0e17 \u0e1c\u0e14\u0e38\u0e07\u0e28\u0e34\u0e25\u0e1b\u0e4c\u0e42\u0e22\u0e18\u0e32\u0e01\u0e32\u0e23 \u0e08\u0e33\u0e01\u0e31\u0e14 \u0e23\u0e48\u0e27\u0e21\u0e41\u0e2a\u0e14\u0e07\u0e04\u0e27\u0e32\u0e21\u0e22\u0e34\u0e19\u0e14\u0e35\u0e43\u0e19\u0e42\u0e2d\u0e01\u0e32\u0e2a\u0e40\u0e1b\u0e34\u0e14\u0e2a\u0e16\u0e32\u0e19\u0e35\u0e1a\u0e23\u0e34\u0e01\u0e32\u0e23\u0e19\u0e49\u0e33\u0e21\u0e31\u0e19 \u0e1b\u0e15\u0e17. \u0e1a\u0e08\u0e01. \u0e40\u0e2d\u0e0a \u0e0b\u0e35 \u0e40\u0e2d\u0e47\u0e19 \u0e40\u0e2d\u0e47\u0e19\u0e40\u0e19\u0e2d\u0e23\u0e4c\u0e08\u0e35 \u0e08\u0e33\u0e01\u0e31\u0e14"
                              }
                            </div>
                          </React.Fragment>
                        ),
                        value: args.slot4
                      })}
                    </Stack__>
                  </Stack__>
                </div>
                <div className={classNames(projectcss.all, sty.column___70Alq)}>
                  <Stack__
                    as={PlasmicLink__}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__nwemw
                    )}
                    component={Link}
                    href={`/PERMATANK และถังน้ำมันแบบต่างๆ`}
                    platform={"nextjs"}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__knOhx)}
                    >
                      {renderPlasmicSlot({
                        defaultContents: (
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__ocsCp)}
                            displayHeight={"250px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/psd_j/images/_16962945840002154633914967365690975083369688NJpg.jpg",
                              fullWidth: 1600,
                              fullHeight: 1200,
                              aspectRatio: undefined
                            }}
                          />
                        ),

                        value: args.pic5
                      })}
                    </div>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__jY9W)}
                    >
                      {renderPlasmicSlot({
                        defaultContents: (
                          <React.Fragment>
                            <Stack__
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__lhGSq
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__db3C
                                )}
                              >
                                <_14655891761535698998SvgIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__ks5Z8
                                  )}
                                  role={"img"}
                                />
                              </div>
                              <Stack__
                                as={"div"}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox___5A0Kg
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__gVAt
                                  )}
                                >
                                  {
                                    "\u0e18\u0e31\u0e19\u0e27\u0e32\u0e04\u0e21 27, 2024"
                                  }
                                </div>
                              </Stack__>
                            </Stack__>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__iKgo
                              )}
                            >
                              {
                                "\u0e1c\u0e39\u0e49\u0e1a\u0e23\u0e34\u0e2b\u0e32\u0e23\u0e1a\u0e23\u0e34\u0e29\u0e31\u0e17 \u0e1c\u0e14\u0e38\u0e07\u0e28\u0e34\u0e25\u0e1b\u0e4c\u0e42\u0e22\u0e18\u0e32\u0e01\u0e32\u0e23 \u0e08\u0e33\u0e01\u0e31\u0e14 \u0e23\u0e48\u0e27\u0e21\u0e41\u0e2a\u0e14\u0e07\u0e04\u0e27\u0e32\u0e21\u0e22\u0e34\u0e19\u0e14\u0e35\u0e43\u0e19\u0e42\u0e2d\u0e01\u0e32\u0e2a\u0e40\u0e1b\u0e34\u0e14\u0e2a\u0e16\u0e32\u0e19\u0e35\u0e1a\u0e23\u0e34\u0e01\u0e32\u0e23\u0e19\u0e49\u0e33\u0e21\u0e31\u0e19 \u0e1b\u0e15\u0e17. \u0e1a\u0e08\u0e01. \u0e08\u0e34\u0e14\u0e32\u0e20\u0e32 \u0e1b\u0e34\u0e42\u0e15\u0e23\u0e40\u0e25\u0e35\u0e22\u0e21 \u0e08\u0e31\u0e07\u0e2b\u0e27\u0e31\u0e14\u0e0a\u0e25\u0e1a\u0e38\u0e23\u0e35"
                              }
                            </div>
                          </React.Fragment>
                        ),
                        value: args.slot5
                      })}
                    </Stack__>
                  </Stack__>
                </div>
                <div className={classNames(projectcss.all, sty.column__x5IcO)}>
                  <Stack__
                    as={PlasmicLink__}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__unWf3
                    )}
                    component={Link}
                    href={`/PERMATANK และถังน้ำมันแบบต่างๆ`}
                    platform={"nextjs"}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__bhcWj)}
                    >
                      {renderPlasmicSlot({
                        defaultContents: (
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img___0587K)}
                            displayHeight={"250px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/psd_j/images/_3149430817600204340776888085103392998817792NJpg.jpg",
                              fullWidth: 960,
                              fullHeight: 720,
                              aspectRatio: undefined
                            }}
                          />
                        ),

                        value: args.pic6
                      })}
                    </div>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__gkfdx)}
                    >
                      {renderPlasmicSlot({
                        defaultContents: (
                          <React.Fragment>
                            <Stack__
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__nzuxT
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__qiPw0
                                )}
                              >
                                <_14655891761535698998SvgIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__rdJq
                                  )}
                                  role={"img"}
                                />
                              </div>
                              <Stack__
                                as={"div"}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__xOPs
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text___1DFnw
                                  )}
                                >
                                  {
                                    "\u0e18\u0e31\u0e19\u0e27\u0e32\u0e04\u0e21 27, 2024"
                                  }
                                </div>
                              </Stack__>
                            </Stack__>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__t9H6
                              )}
                            >
                              {
                                "\u0e1a\u0e23\u0e34\u0e29\u0e31\u0e17 \u0e1c\u0e14\u0e38\u0e07\u0e28\u0e34\u0e25\u0e1b\u0e4c\u0e27\u0e34\u0e28\u0e27\u0e01\u0e32\u0e23 \u0e08\u0e33\u0e01\u0e31\u0e14 \u0e15\u0e34\u0e14\u0e15\u0e31\u0e49\u0e07 Frp Watertight tank sump \u0e17\u0e35\u0e48 \u0e08.\u0e1b\u0e23\u0e32\u0e08\u0e35\u0e19\u0e1a\u0e38\u0e23\u0e35"
                              }
                            </div>
                          </React.Fragment>
                        ),
                        value: args.slot6
                      })}
                    </Stack__>
                  </Stack__>
                </div>
                <div className={classNames(projectcss.all, sty.column___8HdXt)}>
                  <Stack__
                    as={PlasmicLink__}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__wk43U
                    )}
                    component={Link}
                    href={`/PERMATANK และถังน้ำมันแบบต่างๆ`}
                    platform={"nextjs"}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__yBfMu)}
                    >
                      {renderPlasmicSlot({
                        defaultContents: (
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__zLJvn)}
                            displayHeight={"250px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/psd_j/images/_3149430817600204340776888085103392998817792NJpg.jpg",
                              fullWidth: 960,
                              fullHeight: 720,
                              aspectRatio: undefined
                            }}
                          />
                        ),

                        value: args.pic7
                      })}
                    </div>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox___7ZMj)}
                    >
                      {renderPlasmicSlot({
                        defaultContents: (
                          <React.Fragment>
                            <Stack__
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox___7DxJr
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__mnY6N
                                )}
                              >
                                <_14655891761535698998SvgIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__idBox
                                  )}
                                  role={"img"}
                                />
                              </div>
                              <Stack__
                                as={"div"}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox___8Dgyk
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text___3AZgD
                                  )}
                                >
                                  {
                                    "\u0e18\u0e31\u0e19\u0e27\u0e32\u0e04\u0e21 27, 2024"
                                  }
                                </div>
                              </Stack__>
                            </Stack__>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__gtThB
                              )}
                            >
                              {
                                "\u0e1a\u0e23\u0e34\u0e29\u0e31\u0e17 \u0e1c\u0e14\u0e38\u0e07\u0e28\u0e34\u0e25\u0e1b\u0e4c\u0e27\u0e34\u0e01\u0e32\u0e23 \u0e08\u0e33\u0e01\u0e31\u0e14 \u0e1c\u0e48\u0e32\u0e19\u0e01\u0e32\u0e23\u0e15\u0e23\u0e27\u0e08\u0e1b\u0e23\u0e30\u0e40\u0e21\u0e34\u0e19\u0e14\u0e49\u0e32\u0e19\u0e2a\u0e34\u0e48\u0e07\u0e41\u0e27\u0e14\u0e25\u0e49\u0e2d\u0e21 \u0e2a\u0e31\u0e07\u0e04\u0e21 \u0e41\u0e25\u0e30\u0e01\u0e32\u0e23\u0e01\u0e33\u0e01\u0e31\u0e1a\u0e14\u0e39\u0e41\u0e25\u0e01\u0e34\u0e08\u0e01\u0e32\u0e23 \u0e08\u0e32\u0e01\u0e1a\u0e23\u0e34\u0e29\u0e31\u0e17 \u0e1e\u0e35\u0e17\u0e35\u0e08\u0e35 \u0e40\u0e2d\u0e47\u0e19\u0e40\u0e19\u0e2d\u0e22\u0e35 \u0e08\u0e33\u0e01\u0e31\u0e14 (\u0e21\u0e2b\u0e32\u0e0a\u0e19)"
                              }
                            </div>
                          </React.Fragment>
                        ),
                        value: args.slot7
                      })}
                    </Stack__>
                  </Stack__>
                </div>
                <div className={classNames(projectcss.all, sty.column__plToT)}>
                  <Stack__
                    as={PlasmicLink__}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__eafNg
                    )}
                    component={Link}
                    href={`/PERMATANK และถังน้ำมันแบบต่างๆ`}
                    platform={"nextjs"}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__aTnzy)}
                    >
                      {renderPlasmicSlot({
                        defaultContents: (
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__jBjjI)}
                            displayHeight={"250px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/psd_j/images/_3149430817600204340776888085103392998817792NJpg.jpg",
                              fullWidth: 960,
                              fullHeight: 720,
                              aspectRatio: undefined
                            }}
                          />
                        ),

                        value: args.pic8
                      })}
                    </div>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__d9Czg)}
                    >
                      {renderPlasmicSlot({
                        defaultContents: (
                          <React.Fragment>
                            <Stack__
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__llrXb
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__vQwyj
                                )}
                              >
                                <_14655891761535698998SvgIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__cyEAr
                                  )}
                                  role={"img"}
                                />
                              </div>
                              <Stack__
                                as={"div"}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__igulP
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__jo4A
                                  )}
                                >
                                  {
                                    "\u0e18\u0e31\u0e19\u0e27\u0e32\u0e04\u0e21 27, 2024"
                                  }
                                </div>
                              </Stack__>
                            </Stack__>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ed3KP
                              )}
                            >
                              {
                                "\u0e1a\u0e23\u0e34\u0e29\u0e31\u0e17\u0e1c\u0e14\u0e38\u0e07\u0e28\u0e34\u0e25\u0e1b\u0e4c\u0e42\u0e22\u0e18\u0e32\u0e01\u0e32\u0e23\u0e08\u0e33\u0e01\u0e31\u0e14\u0e44\u0e14\u0e49\u0e17\u0e33\u0e01\u0e32\u0e23\u0e15\u0e34\u0e14\u0e15\u0e31\u0e49\u0e07\u0e40\u0e2a\u0e32\u0e1b\u0e49\u0e32\u0e22 Hiway Sign \u0e02\u0e19\u0e32\u0e14 24 \u0e40\u0e21\u0e15\u0e23 \u0e2a\u0e33\u0e2b\u0e23\u0e31\u0e1a\u0e42\u0e04\u0e23\u0e07\u0e01\u0e32\u0e23\u0e01\u0e48\u0e2d\u0e2a\u0e23\u0e49\u0e32\u0e07\u0e2a\u0e16\u0e32\u0e19\u0e35\u0e1a\u0e23\u0e34\u0e01\u0e32\u0e23\u0e19\u0e49\u0e33\u0e21\u0e31\u0e19 \u0e1b\u0e15\u0e17. \u0e08\u0e34\u0e14\u0e32\u0e20\u0e32 \u0e1b\u0e34\u0e42\u0e15\u0e23\u0e40\u0e25\u0e35\u0e22\u0e21 \u0e43\u0e19\u0e2d\u0e33\u0e40\u0e20\u0e2d\u0e1a\u0e49\u0e32\u0e19\u0e1a\u0e36\u0e07 \u0e08\u0e31\u0e07\u0e2b\u0e27\u0e31\u0e14\u0e0a\u0e25\u0e1a\u0e38\u0e23\u0e35"
                              }
                            </div>
                          </React.Fragment>
                        ),
                        value: args.slot8
                      })}
                    </Stack__>
                  </Stack__>
                </div>
                <div className={classNames(projectcss.all, sty.column__cEsmt)}>
                  <Stack__
                    as={PlasmicLink__}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link___55Lti
                    )}
                    component={Link}
                    href={`/PERMATANK และถังน้ำมันแบบต่างๆ`}
                    platform={"nextjs"}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__m1RJy)}
                    >
                      {renderPlasmicSlot({
                        defaultContents: (
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__jdAjQ)}
                            displayHeight={"250px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/psd_j/images/_3149430817600204340776888085103392998817792NJpg.jpg",
                              fullWidth: 960,
                              fullHeight: 720,
                              aspectRatio: undefined
                            }}
                          />
                        ),

                        value: args.pic9
                      })}
                    </div>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__kjpIa)}
                    >
                      {renderPlasmicSlot({
                        defaultContents: (
                          <React.Fragment>
                            <Stack__
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__dx1V4
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__imd8
                                )}
                              >
                                <_14655891761535698998SvgIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__qgUm
                                  )}
                                  role={"img"}
                                />
                              </div>
                              <Stack__
                                as={"div"}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox___7VMam
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__qeyV
                                  )}
                                >
                                  {
                                    "\u0e18\u0e31\u0e19\u0e27\u0e32\u0e04\u0e21 27, 2024"
                                  }
                                </div>
                              </Stack__>
                            </Stack__>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__gyj6G
                              )}
                            >
                              {
                                "\u0e1a\u0e23\u0e34\u0e29\u0e31\u0e17 \u0e1c\u0e14\u0e38\u0e07\u0e28\u0e34\u0e25\u0e1b\u0e4c\u0e27\u0e34\u0e28\u0e27\u0e01\u0e32\u0e23 \u0e08\u0e33\u0e01\u0e31\u0e14 \u0e44\u0e14\u0e49\u0e43\u0e2b\u0e49\u0e01\u0e32\u0e23\u0e15\u0e49\u0e2d\u0e19\u0e23\u0e31\u0e1a Mr. Ian R. Dixon (Quality Inspector) \u0e08\u0e32\u0e01 Steel Tank Institute \u2013 Steel Plate Fabrication Association (STI)"
                              }
                            </div>
                          </React.Fragment>
                        ),
                        value: args.slot9
                      })}
                    </Stack__>
                  </Stack__>
                </div>
                <div className={classNames(projectcss.all, sty.column__er6P9)}>
                  <Stack__
                    as={PlasmicLink__}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__h4KS
                    )}
                    component={Link}
                    href={`/PERMATANK และถังน้ำมันแบบต่างๆ`}
                    platform={"nextjs"}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__s7QvX)}
                    >
                      {renderPlasmicSlot({
                        defaultContents: (
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__bTQef)}
                            displayHeight={"250px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/psd_j/images/_3149430817600204340776888085103392998817792NJpg.jpg",
                              fullWidth: 960,
                              fullHeight: 720,
                              aspectRatio: undefined
                            }}
                          />
                        ),

                        value: args.pic10
                      })}
                    </div>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___3ZTRz
                      )}
                    >
                      {renderPlasmicSlot({
                        defaultContents: (
                          <React.Fragment>
                            <Stack__
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox___9PgX
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__umYYm
                                )}
                              >
                                <_14655891761535698998SvgIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__j3IfL
                                  )}
                                  role={"img"}
                                />
                              </div>
                              <Stack__
                                as={"div"}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__isnqh
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__dlk7K
                                  )}
                                >
                                  {
                                    "\u0e18\u0e31\u0e19\u0e27\u0e32\u0e04\u0e21 27, 2024"
                                  }
                                </div>
                              </Stack__>
                            </Stack__>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__fjKjG
                              )}
                            >
                              {
                                "\u0e1a\u0e23\u0e34\u0e29\u0e31\u0e17 \u0e1c\u0e14\u0e38\u0e07\u0e28\u0e34\u0e25\u0e1b\u0e4c\u0e27\u0e34\u0e28\u0e27\u0e01\u0e32\u0e23 \u0e08\u0e33\u0e01\u0e31\u0e14 \u0e02\u0e2d\u0e02\u0e2d\u0e1a\u0e1e\u0e23\u0e30\u0e04\u0e38\u0e13\u0e25\u0e39\u0e01\u0e04\u0e49\u0e32\u0e08\u0e32\u0e01\u0e1b\u0e23\u0e30\u0e40\u0e17\u0e28\u0e40\u0e1e\u0e37\u0e48\u0e2d\u0e19\u0e1a\u0e49\u0e32\u0e19\u0e17\u0e35\u0e48\u0e44\u0e27\u0e49\u0e27\u0e32\u0e07\u0e43\u0e08\u0e2a\u0e31\u0e48\u0e07\u0e0b\u0e37\u0e49\u0e2d\u0e16\u0e31\u0e07\u0e19\u0e49\u0e33\u0e21\u0e31\u0e19\u0e43\u0e15\u0e49\u0e14\u0e34\u0e19\u0e2a\u0e2d\u0e07\u0e0a\u0e31\u0e49\u0e19 \u0e02\u0e19\u0e32\u0e14 30,000 \u0e25\u0e34\u0e15\u0e23\u0e08\u0e32\u0e01\u0e40\u0e23\u0e32"
                              }
                            </div>
                          </React.Fragment>
                        ),
                        value: args.slot10
                      })}
                    </Stack__>
                  </Stack__>
                </div>
              </Stack__>
            </Stack__>
          </Stack__>
          <Footer2
            data-plasmic-name={"footer2"}
            data-plasmic-override={overrides.footer2}
            className={classNames("__wab_instance", sty.footer2)}
          />
        </Stack__>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  page: [
    "page",
    "header",
    "bannerHeader",
    "h1",
    "productAndService",
    "columns",
    "footer2"
  ],
  header: ["header"],
  bannerHeader: ["bannerHeader", "h1"],
  h1: ["h1"],
  productAndService: ["productAndService", "columns"],
  columns: ["columns"],
  footer2: ["footer2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  page: "div";
  header: typeof Header;
  bannerHeader: "div";
  h1: "h1";
  productAndService: "div";
  columns: "div";
  footer2: typeof Footer2;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNewsAndActivity__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNewsAndActivity__VariantsArgs;
    args?: PlasmicNewsAndActivity__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicNewsAndActivity__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicNewsAndActivity__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNewsAndActivity__ArgProps,
          internalVariantPropNames: PlasmicNewsAndActivity__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNewsAndActivity__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "page") {
    func.displayName = "PlasmicNewsAndActivity";
  } else {
    func.displayName = `PlasmicNewsAndActivity.${nodeName}`;
  }
  return func;
}

export const PlasmicNewsAndActivity = Object.assign(
  // Top-level PlasmicNewsAndActivity renders the root element
  makeNodeComponent("page"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    bannerHeader: makeNodeComponent("bannerHeader"),
    h1: makeNodeComponent("h1"),
    productAndService: makeNodeComponent("productAndService"),
    columns: makeNodeComponent("columns"),
    footer2: makeNodeComponent("footer2"),

    // Metadata about props expected for PlasmicNewsAndActivity
    internalVariantProps: PlasmicNewsAndActivity__VariantProps,
    internalArgProps: PlasmicNewsAndActivity__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicNewsAndActivity;
/* prettier-ignore-end */
